import { SymposiumEvent, Attendee, Team, Host, Judge } from './types';

export const INITIAL_EVENTS: SymposiumEvent[] = [
  {
    id: 'paper_presentation',
    eventId: 'paper_presentation',
    title: 'Paper Presentation',
    eventName: 'Paper Presentation',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Technical Presentation Event',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'paperpresentation@aitheronml.in',
    hostName: 'Paper Presentation Host',
    icon: 'FileText',
    location: 'Seminar Hall 1 (Block A)',
    venue: 'Seminar Hall 1 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_paper'],
    judgeIds: ['judge_paper'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'poster_presentation',
    eventId: 'poster_presentation',
    title: 'Poster Presentation',
    eventName: 'Poster Presentation',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Technical Innovation Event',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'posterpresentation@aitheronml.in',
    hostName: 'Poster Presentation Host',
    icon: 'Layers',
    location: 'Mechanical Seminar Hall',
    venue: 'Mechanical Seminar Hall',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_poster'],
    judgeIds: ['judge_poster'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'vibe_coding',
    eventId: 'vibe_coding',
    title: 'White Coding',
    eventName: 'White Coding',
    track: 'Technical',
    category: 'Technical',
    session: 'Afternoon Session',
    subtitle: 'High-speed Logic & Coding Contest',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'vibecoding@aitheronml.in',
    hostName: 'White Coding Host',
    icon: 'Brain',
    location: 'CSE Lab 3 (Block B)',
    venue: 'CSE Lab 3 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_vibe'],
    judgeIds: ['judge_vibe'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'project_expo',
    eventId: 'project_expo',
    title: 'Project Expo',
    eventName: 'Project Expo',
    track: 'Technical',
    category: 'Technical',
    session: 'Full-Day Session',
    subtitle: 'Technical Prototype Showcase',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'projectexpo@aitheronml.in',
    hostName: 'Project Expo Host',
    icon: 'Award',
    location: 'Main Block Corridor',
    venue: 'Main Block Corridor',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_project'],
    judgeIds: ['judge_project'],
    minimumTeamSize: 1,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'photography',
    eventId: 'photography',
    title: 'Photography',
    eventName: 'Photography',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Creative Lens & Angle Contest',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'photography@aitheronml.in',
    hostName: 'Photography Host',
    icon: 'Camera',
    location: 'Entire Campus grounds',
    venue: 'Entire Campus grounds',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_photo'],
    judgeIds: ['judge_photo'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'treasure_hunt',
    eventId: 'treasure_hunt',
    title: 'Treasure Hunt',
    eventName: 'Treasure Hunt',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Campus-wide Mystery Clues Race',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'treasurehunt@aitheronml.in',
    hostName: 'Treasure Hunt Host',
    icon: 'Map',
    location: 'Campus Open Air Theatre',
    venue: 'Campus Open Air Theatre',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_treasure'],
    judgeIds: ['judge_treasure'],
    minimumTeamSize: 2,
    maximumTeamSize: 5,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'free_fire',
    eventId: 'free_fire',
    title: 'Free Fire',
    eventName: 'Free Fire',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Squad Battle Royale Esports',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'freefire@aitheronml.in',
    hostName: 'Free Fire Host',
    icon: 'Gamepad2',
    location: 'ECE Lab 1 (Block C)',
    venue: 'ECE Lab 1 (Block C)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_free'],
    judgeIds: ['judge_free'],
    minimumTeamSize: 4,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'dumb_charades',
    eventId: 'dumb_charades',
    title: 'Dumb Charades',
    eventName: 'Dumb Charades',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Expression, Gesture & Movie Guessing',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'dumbcharades@aitheronml.in',
    hostName: 'Dumb Charades Host',
    icon: 'Users',
    location: 'Seminar Hall 2 (Block A)',
    venue: 'Seminar Hall 2 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_dumb'],
    judgeIds: ['judge_dumb'],
    minimumTeamSize: 3,
    maximumTeamSize: 3,
    checkedInCount: 0,
    winnerIds: []
  }
];

export const INITIAL_ATTENDEES: Attendee[] = [];

// Replaced/mock structures to keep legacy code compiling
export const INITIAL_SPEAKERS: any[] = [];
export const INITIAL_SUBMISSIONS: any[] = [];
