import { SymposiumEvent, Attendee } from './types';

export const INITIAL_EVENTS: SymposiumEvent[] = [
  // --- Technical Events ---
  {
    id: 'paper_presentation',
    eventId: 'paper_presentation',
    title: 'Paper Presentation',
    eventName: 'Paper Presentation',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Technical Presentation Event',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'paperpresentation@aitheronml.in',
    hostName: 'Gauthami & Charan.P',
    icon: 'FileText',
    location: 'Seminar Hall 1 (Block A)',
    venue: 'Seminar Hall 1 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_paper'],
    judgeIds: ['judge_paper'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'project_expo',
    eventId: 'project_expo',
    title: 'Project Expo',
    eventName: 'Project Expo',
    track: 'Technical',
    category: 'Technical',
    session: 'Full-Day Session',
    subtitle: 'Technical Prototype Showcase',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'projectexpo@aitheronml.in',
    hostName: 'Mounika & B Pavani',
    icon: 'Award',
    location: 'Main Block Corridor',
    venue: 'Main Block Corridor',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_project'],
    judgeIds: ['judge_project'],
    minimumTeamSize: 1,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'ai_agent_challenge',
    eventId: 'ai_agent_challenge',
    title: 'AI Agent Challenge',
    eventName: 'AI Agent Challenge',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Autonomous Agent Development Hack',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'aiagent@aitheronml.in',
    hostName: 'Tharun K & O S Praveen',
    icon: 'Cpu',
    location: 'CSE Lab 1 (Block B)',
    venue: 'CSE Lab 1 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_ai_agent'],
    judgeIds: ['judge_ai_agent'],
    minimumTeamSize: 1,
    maximumTeamSize: 3,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'ai_video_generation',
    eventId: 'ai_video_generation',
    title: 'AI Video Generation',
    eventName: 'AI Video Generation',
    track: 'Technical',
    category: 'Technical',
    session: 'Afternoon Session',
    subtitle: 'Cinematic AI Video Creation & Prompting',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'aivideo@aitheronml.in',
    hostName: 'Vignati & Akshaya',
    icon: 'Tv',
    location: 'CSE Lab 2 (Block B)',
    venue: 'CSE Lab 2 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_ai_video'],
    judgeIds: ['judge_ai_video'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'dsa_challenge',
    eventId: 'dsa_challenge',
    title: 'DSA Challenge',
    eventName: 'DSA Challenge',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Data Structures & Algorithms Coding Match',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'dsa@aitheronml.in',
    hostName: 'C.Raghavendra & Kesiya',
    icon: 'Code',
    location: 'CSE Lab 4 (Block B)',
    venue: 'CSE Lab 4 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_dsa'],
    judgeIds: ['judge_dsa'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'vibe_coding',
    eventId: 'vibe_coding',
    title: 'Vibe Coding',
    eventName: 'Vibe Coding',
    track: 'Technical',
    category: 'Technical',
    session: 'Afternoon Session',
    subtitle: 'High-speed Logic & Coding Contest',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'vibecoding@aitheronml.in',
    hostName: 'Deekshitha & B S Nandini',
    icon: 'Brain',
    location: 'CSE Lab 3 (Block B)',
    venue: 'CSE Lab 3 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_vibe'],
    judgeIds: ['judge_vibe'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'technical_quiz',
    eventId: 'technical_quiz',
    title: 'Technical Quiz',
    eventName: 'Technical Quiz',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'CS and Tech Trivia Challenge',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'techquiz@aitheronml.in',
    hostName: 'Charan Teja & Akash',
    icon: 'HelpCircle',
    location: 'Seminar Hall 2 (Block A)',
    venue: 'Seminar Hall 2 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_quiz'],
    judgeIds: ['judge_quiz'],
    minimumTeamSize: 2,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },

  // --- Non-Technical Events ---
  {
    id: 'photography',
    eventId: 'photography',
    title: 'Photography',
    eventName: 'Photography',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Creative Lens & Angle Contest',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'photography@aitheronml.in',
    hostName: 'Arif & Nikitha',
    icon: 'Camera',
    location: 'Entire Campus Grounds',
    venue: 'Entire Campus Grounds',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_photo'],
    judgeIds: ['judge_photo'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'logo_identification',
    eventId: 'logo_identification',
    title: 'Logo Identification',
    eventName: 'Logo Identification',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Identify Famous Brand Logos',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'logo@aitheronml.in',
    hostName: 'Pranav & Zaara',
    icon: 'Sparkles',
    location: 'Mechanical Seminar Hall',
    venue: 'Mechanical Seminar Hall',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_logo'],
    judgeIds: ['judge_logo'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'treasure_hunt',
    eventId: 'treasure_hunt',
    title: 'Treasure Hunt',
    eventName: 'Treasure Hunt',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Campus-wide Mystery Clues Race',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'treasurehunt@aitheronml.in',
    hostName: 'Vivek & Indumathi',
    icon: 'Map',
    location: 'Campus Open Air Theatre',
    venue: 'Campus Open Air Theatre',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_treasure'],
    judgeIds: ['judge_treasure'],
    minimumTeamSize: 2,
    maximumTeamSize: 5,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'freefire',
    eventId: 'freefire',
    title: 'Freefire',
    eventName: 'Freefire',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Squad Battle Royale Esports',
    registeredCount: 0,
    status: 'Upcoming',
    hostEmail: 'freefire@aitheronml.in',
    hostName: 'Thoufiq & Sarkesh',
    icon: 'Gamepad2',
    location: 'ECE Lab 1 (Block C)',
    venue: 'ECE Lab 1 (Block C)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_free'],
    judgeIds: ['judge_free'],
    minimumTeamSize: 4,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  }
];

export const INITIAL_ATTENDEES: Attendee[] = [];
export const INITIAL_SPEAKERS: any[] = [];
export const INITIAL_SUBMISSIONS: any[] = [];
