import { SymposiumEvent, Attendee, Team, Host, Judge } from './types';

export const INITIAL_EVENTS: SymposiumEvent[] = [
  {
    id: 'paper_presentation',
    eventId: 'paper_presentation',
    title: 'Paper Presentation',
    eventName: 'Paper Presentation',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Technical Presentation Event',
    registeredCount: 45,
    status: 'Upcoming',
    hostEmail: 'paperpresentation@aitheronml.in',
    hostName: 'Paper Presentation Host',
    icon: 'FileText',
    location: 'Seminar Hall 1 (Block A)',
    venue: 'Seminar Hall 1 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_paper'],
    judgeIds: ['judge_paper'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'poster_presentation',
    eventId: 'poster_presentation',
    title: 'Poster Presentation',
    eventName: 'Poster Presentation',
    track: 'Technical',
    category: 'Technical',
    session: 'Morning Session',
    subtitle: 'Technical Innovation Event',
    registeredCount: 32,
    status: 'Upcoming',
    hostEmail: 'posterpresentation@aitheronml.in',
    hostName: 'Poster Presentation Host',
    icon: 'Layers',
    location: 'Mechanical Seminar Hall',
    venue: 'Mechanical Seminar Hall',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_poster'],
    judgeIds: ['judge_poster'],
    minimumTeamSize: 1,
    maximumTeamSize: 2,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'vibe_coding',
    eventId: 'vibe_coding',
    title: 'White Coding',
    eventName: 'White Coding',
    track: 'Technical',
    category: 'Technical',
    session: 'Afternoon Session',
    subtitle: 'High-speed Logic & Coding Contest',
    registeredCount: 68,
    status: 'Upcoming',
    hostEmail: 'vibecoding@aitheronml.in',
    hostName: 'White Coding Host',
    icon: 'Brain',
    location: 'CSE Lab 3 (Block B)',
    venue: 'CSE Lab 3 (Block B)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_vibe'],
    judgeIds: ['judge_vibe'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'project_expo',
    eventId: 'project_expo',
    title: 'Project Expo',
    eventName: 'Project Expo',
    track: 'Technical',
    category: 'Technical',
    session: 'Full-Day Session',
    subtitle: 'Technical Prototype Showcase',
    registeredCount: 28,
    status: 'Upcoming',
    hostEmail: 'projectexpo@aitheronml.in',
    hostName: 'Project Expo Host',
    icon: 'Award',
    location: 'Main Block Corridor',
    venue: 'Main Block Corridor',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_project'],
    judgeIds: ['judge_project'],
    minimumTeamSize: 1,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'photography',
    eventId: 'photography',
    title: 'Photography',
    eventName: 'Photography',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Creative Lens & Angle Contest',
    registeredCount: 40,
    status: 'Upcoming',
    hostEmail: 'photography@aitheronml.in',
    hostName: 'Photography Host',
    icon: 'Camera',
    location: 'Entire Campus grounds',
    venue: 'Entire Campus grounds',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_photo'],
    judgeIds: ['judge_photo'],
    minimumTeamSize: 1,
    maximumTeamSize: 1,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'treasure_hunt',
    eventId: 'treasure_hunt',
    title: 'Treasure Hunt',
    eventName: 'Treasure Hunt',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Campus-wide Mystery Clues Race',
    registeredCount: 150,
    status: 'Upcoming',
    hostEmail: 'treasurehunt@aitheronml.in',
    hostName: 'Treasure Hunt Host',
    icon: 'Map',
    location: 'Campus Open Air Theatre',
    venue: 'Campus Open Air Theatre',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_treasure'],
    judgeIds: ['judge_treasure'],
    minimumTeamSize: 2,
    maximumTeamSize: 5,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'free_fire',
    eventId: 'free_fire',
    title: 'Free Fire',
    eventName: 'Free Fire',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Afternoon Session',
    subtitle: 'Squad Battle Royale Esports',
    registeredCount: 96,
    status: 'Upcoming',
    hostEmail: 'freefire@aitheronml.in',
    hostName: 'Free Fire Host',
    icon: 'Gamepad2',
    location: 'ECE Lab 1 (Block C)',
    venue: 'ECE Lab 1 (Block C)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_free'],
    judgeIds: ['judge_free'],
    minimumTeamSize: 4,
    maximumTeamSize: 4,
    checkedInCount: 0,
    winnerIds: []
  },
  {
    id: 'dumb_charades',
    eventId: 'dumb_charades',
    title: 'Dumb Charades',
    eventName: 'Dumb Charades',
    track: 'Non-Technical',
    category: 'Non-Technical',
    session: 'Morning Session',
    subtitle: 'Expression, Gesture & Movie Guessing',
    registeredCount: 30,
    status: 'Upcoming',
    hostEmail: 'dumbcharades@aitheronml.in',
    hostName: 'Dumb Charades Host',
    icon: 'Users',
    location: 'Seminar Hall 2 (Block A)',
    venue: 'Seminar Hall 2 (Block A)',
    resultsSubmitted: false,
    eventDate: '2026-07-15',
    registrationOpen: true,
    registrationClose: false,
    hostIds: ['host_dumb'],
    judgeIds: ['judge_dumb'],
    minimumTeamSize: 3,
    maximumTeamSize: 3,
    checkedInCount: 0,
    winnerIds: []
  }
];

export const INITIAL_ATTENDEES: Attendee[] = [
  {
    id: 'SYM-000001',
    participantId: 'SYM-000001',
    name: 'Suresh Kumar',
    email: 'suresh.k@gmail.com',
    phone: '9876543210',
    college: 'Kuppam Engineering College',
    registeredEventId: 'paper_presentation',
    eventId: 'paper_presentation',
    registeredEventTitle: 'Paper Presentation',
    attendanceStatus: 'Present',
    branch: 'Computer Science',
    year: '3rd Year',
    regType: 'individual',
    registrationType: 'individual',
    registrationDate: '2026-07-01T10:00:00.000Z',
    accessLevel: 'Individual Pass',
    secureToken: 'SYM-000001',
    qrCode: 'SYM-000001'
  },
  {
    id: 'SYM-000002',
    participantId: 'SYM-000002',
    name: 'Ananya Reddy',
    email: 'ananya.r@yahoo.com',
    phone: '8765432109',
    college: 'MITS, Madanapalle',
    registeredEventId: 'paper_presentation',
    eventId: 'paper_presentation',
    registeredEventTitle: 'Paper Presentation',
    attendanceStatus: 'Present',
    branch: 'Information Technology',
    year: '4th Year',
    regType: 'individual',
    registrationType: 'individual',
    registrationDate: '2026-07-02T11:30:00.000Z',
    accessLevel: 'Individual Pass',
    secureToken: 'SYM-000002',
    qrCode: 'SYM-000002'
  },
  {
    id: 'SYM-000003',
    participantId: 'SYM-000003',
    name: 'Rohan Sharma',
    email: 'rohan.s@gmail.com',
    phone: '7654321098',
    college: 'Vellore Institute of Technology',
    registeredEventId: 'vibe_coding',
    eventId: 'vibe_coding',
    registeredEventTitle: 'White Coding',
    attendanceStatus: 'Present',
    branch: 'Software Engineering',
    year: '2nd Year',
    regType: 'individual',
    registrationType: 'individual',
    registrationDate: '2026-07-03T14:20:00.000Z',
    accessLevel: 'Individual Pass',
    secureToken: 'SYM-000003',
    qrCode: 'SYM-000003'
  },
  {
    id: 'SYM-000004',
    participantId: 'SYM-000004',
    name: 'Pooja Hegde',
    email: 'pooja.h@gmail.com',
    phone: '6543210987',
    college: 'Kuppam Engineering College',
    registeredEventId: 'vibe_coding',
    eventId: 'vibe_coding',
    registeredEventTitle: 'White Coding',
    attendanceStatus: 'Pending',
    branch: 'Electronics & Communication',
    year: '3rd Year',
    regType: 'individual',
    registrationType: 'individual',
    registrationDate: '2026-07-04T09:15:00.000Z',
    accessLevel: 'Individual Pass',
    secureToken: 'SYM-000004',
    qrCode: 'SYM-000004'
  },
  {
    id: 'SYM-000005',
    participantId: 'SYM-000005',
    name: 'Dinesh Karthik',
    email: 'dinesh.k@outlook.com',
    phone: '9988776655',
    college: 'PES University, Bangalore',
    registeredEventId: 'photography',
    eventId: 'photography',
    registeredEventTitle: 'Photography',
    attendanceStatus: 'Pending',
    branch: 'Computer Science',
    year: '3rd Year',
    regType: 'individual',
    registrationType: 'individual',
    registrationDate: '2026-07-05T15:40:00.000Z',
    accessLevel: 'Individual Pass',
    secureToken: 'SYM-000005',
    qrCode: 'SYM-000005'
  }
];

// Replaced/mock structures to keep legacy code compiling
export const INITIAL_SPEAKERS: any[] = [];
export const INITIAL_SUBMISSIONS: any[] = [];
